//! Git hook installation and management.
//!
//! This module handles the lifecycle of Ralph-managed git hooks, including:
//!
//! - **Installation**: Creating `pre-commit` and `pre-push` hooks that block
//!   git operations during the agent phase (when `.no_agent_commit` exists)
//! - **Backup**: Preserving existing hooks as `.ralph.orig` files before overwriting
//! - **Restoration**: Restoring original hooks when uninstalling Ralph hooks
//!
//! Hooks are identified by a marker string (`RALPH_RUST_MANAGED_HOOK`) embedded
//! in the hook script, allowing safe detection and removal of Ralph-managed hooks
//! without affecting user-created hooks.

use crate::utils::{file_contains_marker, Logger};
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::Command;

/// Marker string for Ralph-managed hooks.
pub(crate) const HOOK_MARKER: &str = "RALPH_RUST_MANAGED_HOOK";

/// Get the git hooks directory path.
fn get_hooks_dir() -> io::Result<PathBuf> {
    let output = Command::new("git")
        .args(["rev-parse", "--git-path", "hooks"])
        .output()?;

    if output.status.success() {
        let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
        Ok(PathBuf::from(path))
    } else {
        Err(io::Error::new(
            io::ErrorKind::NotFound,
            "Unable to resolve git hooks directory",
        ))
    }
}

/// Install a git hook.
pub(crate) fn install_hook(hook_name: &str, hook_path: &Path) -> io::Result<()> {
    // Use absolute path for orig backup.
    let hook_path_abs = fs::canonicalize(hook_path.parent().unwrap_or(Path::new(".")))?
        .join(hook_path.file_name().unwrap_or_default());
    let orig_path = format!("{}.ralph.orig", hook_path_abs.display());

    // Create hooks directory if needed.
    if let Some(parent) = hook_path.parent() {
        fs::create_dir_all(parent)?;
    }

    // Backup existing hook if not already managed by Ralph.
    if hook_path.exists() && !file_contains_marker(hook_path, HOOK_MARKER)? {
        fs::copy(hook_path, &orig_path)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&orig_path)?.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&orig_path, perms)?;
        }
    }

    // Write new hook.
    let hook_content = format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
# {} - generated by ralph

repo_root="$(command git rev-parse --show-toplevel 2>/dev/null || pwd)"
if [[ -f "$repo_root/.no_agent_commit" ]]; then
  echo "✋ {} blocked (agent phase): .no_agent_commit exists."
  exit 1
fi

orig="{}"
if [[ -f "$orig" ]]; then
  exec "$orig" "$@"
fi

exit 0
"#,
        HOOK_MARKER, hook_name, orig_path
    );

    let mut file = File::create(hook_path)?;
    file.write_all(hook_content.as_bytes())?;

    // Make executable.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(hook_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(hook_path, perms)?;
    }

    Ok(())
}

/// Install pre-commit and pre-push hooks.
pub(crate) fn install_hooks() -> io::Result<()> {
    let hooks_dir = get_hooks_dir()?;
    fs::create_dir_all(&hooks_dir)?;

    install_hook("Commit", &hooks_dir.join("pre-commit"))?;
    install_hook("Push", &hooks_dir.join("pre-push"))?;

    Ok(())
}

/// Uninstall a single hook by restoring original or removing.
pub(crate) fn uninstall_hook(hook_path: &Path, logger: &Logger) -> io::Result<bool> {
    let hook_path_abs = if hook_path.is_absolute() {
        hook_path.to_path_buf()
    } else {
        fs::canonicalize(hook_path.parent().unwrap_or(Path::new(".")))?
            .join(hook_path.file_name().unwrap_or_default())
    };
    let orig_path = PathBuf::from(format!("{}.ralph.orig", hook_path_abs.display()));

    // Check if this is a Ralph-managed hook.
    if hook_path.exists() && file_contains_marker(hook_path, HOOK_MARKER)? {
        if orig_path.exists() {
            // Restore original hook.
            fs::rename(&orig_path, hook_path)?;
            let name = hook_path.file_name().unwrap_or_default().to_string_lossy();
            logger.info(&format!("Restored original hook: {}", name));
        } else {
            // No original to restore, just remove.
            fs::remove_file(hook_path)?;
            let name = hook_path.file_name().unwrap_or_default().to_string_lossy();
            logger.info(&format!("Removed hook: {}", name));
        }
        Ok(true)
    } else {
        let name = hook_path.file_name().unwrap_or_default().to_string_lossy();
        logger.warn(&format!("Hook not managed by Ralph: {}", name));
        Ok(false)
    }
}

/// Uninstall all Ralph-managed hooks.
pub(crate) fn uninstall_hooks(logger: &Logger) -> io::Result<()> {
    let hooks_dir = get_hooks_dir()?;
    if !hooks_dir.exists() {
        return Ok(());
    }

    let mut restored = 0;
    for hook_name in &["pre-commit", "pre-push"] {
        let hook_path = hooks_dir.join(hook_name);
        if hook_path.exists() && uninstall_hook(&hook_path, logger)? {
            restored += 1;
        }
    }

    if restored > 0 {
        logger.success(&format!("Uninstalled {} Ralph hook(s)", restored));
    } else {
        logger.info("No Ralph hooks to uninstall");
    }

    Ok(())
}

/// Silently uninstall all Ralph-managed hooks (for signal handlers).
///
/// Does not log output; safe to call during cleanup.
pub(crate) fn uninstall_hooks_silent() {
    let hooks_dir = match get_hooks_dir() {
        Ok(d) => d,
        Err(_) => return,
    };
    if !hooks_dir.exists() {
        return;
    }

    for hook_name in &["pre-commit", "pre-push"] {
        let hook_path = hooks_dir.join(hook_name);
        if hook_path.exists() {
            if let Ok(true) = file_contains_marker(&hook_path, HOOK_MARKER) {
                let hook_path_abs = fs::canonicalize(&hook_path).unwrap_or(hook_path.clone());
                let orig_path = PathBuf::from(format!("{}.ralph.orig", hook_path_abs.display()));

                if orig_path.exists() {
                    let _ = fs::rename(&orig_path, &hook_path);
                } else {
                    let _ = fs::remove_file(&hook_path);
                }
            }
        }
    }
}
