//! Git hook installation and management.
//!
//! This module handles the lifecycle of Ralph-managed git hooks, including:
//!
//! - **Installation**: Creating `pre-commit` and `pre-push` hooks that block
//!   git operations during the agent phase (when `.no_agent_commit` exists)
//! - **Backup**: Preserving existing hooks as `.ralph.orig` files before overwriting
//! - **Restoration**: Restoring original hooks when uninstalling Ralph hooks
//!
//! Hooks are identified by a marker string (`RALPH_RUST_MANAGED_HOOK`) embedded
//! in the hook script, allowing safe detection and removal of Ralph-managed hooks
//! without affecting user-created hooks.
//!
//! Note: This module uses libgit2 (via the repo module) for locating the hooks
//! directory, avoiding CLI dependencies.

use super::repo::get_hooks_dir;
use crate::files::file_contains_marker;
use crate::logger::Logger;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::{Path, PathBuf};

/// Marker string for Ralph-managed hooks.
pub const HOOK_MARKER: &str = "RALPH_RUST_MANAGED_HOOK";

/// Install a git hook.
///
/// The hook script embeds the repository root path directly, avoiding any
/// dependency on the git CLI being installed. The repo root is resolved at
/// installation time using libgit2.
pub fn install_hook(hook_name: &str, hook_path: &Path) -> io::Result<()> {
    use super::repo::get_repo_root;

    // Get the repo root using libgit2 and embed it in the hook script.
    // This avoids any dependency on git CLI being installed.
    let repo_root = get_repo_root()?;
    let repo_root_str = repo_root.display().to_string();

    // Use absolute path for orig backup.
    // Handle the case where hook_path has no parent or file_name gracefully.
    let hook_dir = hook_path.parent().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            "Hook path has no parent directory",
        )
    })?;
    let hook_file_name = hook_path
        .file_name()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "Hook path has no file name"))?;
    let hook_path_abs = fs::canonicalize(hook_dir)?.join(hook_file_name);
    let orig_path = format!("{}.ralph.orig", hook_path_abs.display());

    // Create hooks directory if needed.
    if let Some(parent) = hook_path.parent() {
        fs::create_dir_all(parent)?;
    }

    // Backup existing hook if not already managed by Ralph.
    if hook_path.exists() && !file_contains_marker(hook_path, HOOK_MARKER)? {
        fs::copy(hook_path, &orig_path)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&orig_path)?.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&orig_path, perms)?;
        }
    }

    // Write new hook with repo root embedded directly (no git CLI dependency).
    let hook_content = format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
# {HOOK_MARKER} - generated by ralph
# Repository root (embedded at install time using libgit2): {repo_root_str}

if [[ -f "{repo_root_str}/.no_agent_commit" ]]; then
  echo "✋ {hook_name} blocked (agent phase): .no_agent_commit exists."
  exit 1
fi

orig="{orig_path}"
if [[ -f "$orig" ]]; then
  exec "$orig" "$@"
fi

exit 0
"#
    );

    let mut file = File::create(hook_path)?;
    file.write_all(hook_content.as_bytes())?;

    // Make executable.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(hook_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(hook_path, perms)?;
    }

    Ok(())
}

/// Install pre-commit and pre-push hooks.
pub fn install_hooks() -> io::Result<()> {
    let hooks_dir = get_hooks_dir()?;
    fs::create_dir_all(&hooks_dir)?;

    install_hook("Commit", &hooks_dir.join("pre-commit"))?;
    install_hook("Push", &hooks_dir.join("pre-push"))?;

    Ok(())
}

/// Uninstall a single hook by restoring original or removing.
pub fn uninstall_hook(hook_path: &Path, logger: &Logger) -> io::Result<bool> {
    let hook_path_abs = if hook_path.is_absolute() {
        hook_path.to_path_buf()
    } else {
        // Handle the case where hook_path has no parent or file_name gracefully.
        let hook_dir = hook_path.parent().ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidInput,
                "Hook path has no parent directory",
            )
        })?;
        let hook_file_name = hook_path.file_name().ok_or_else(|| {
            io::Error::new(io::ErrorKind::InvalidInput, "Hook path has no file name")
        })?;
        fs::canonicalize(hook_dir)?.join(hook_file_name)
    };
    let orig_path = PathBuf::from(format!("{}.ralph.orig", hook_path_abs.display()));

    // Check if this is a Ralph-managed hook.
    if hook_path.exists() && file_contains_marker(hook_path, HOOK_MARKER)? {
        if orig_path.exists() {
            // Restore original hook.
            fs::rename(&orig_path, hook_path)?;
            let name = hook_path.file_name().unwrap_or_default().to_string_lossy();
            logger.info(&format!("Restored original hook: {name}"));
        } else {
            // No original to restore, just remove.
            fs::remove_file(hook_path)?;
            let name = hook_path.file_name().unwrap_or_default().to_string_lossy();
            logger.info(&format!("Removed hook: {name}"));
        }
        Ok(true)
    } else {
        let name = hook_path.file_name().unwrap_or_default().to_string_lossy();
        logger.warn(&format!("Hook not managed by Ralph: {name}"));
        Ok(false)
    }
}

/// Uninstall all Ralph-managed hooks.
pub fn uninstall_hooks(logger: &Logger) -> io::Result<()> {
    let hooks_dir = get_hooks_dir()?;
    if !hooks_dir.exists() {
        return Ok(());
    }

    let mut restored = 0;
    for hook_name in &["pre-commit", "pre-push"] {
        let hook_path = hooks_dir.join(hook_name);
        if hook_path.exists() && uninstall_hook(&hook_path, logger)? {
            restored += 1;
        }
    }

    if restored > 0 {
        logger.success(&format!("Uninstalled {restored} Ralph hook(s)"));
    } else {
        logger.info("No Ralph hooks to uninstall");
    }

    Ok(())
}

/// Silently uninstall all Ralph-managed hooks (for signal handlers).
///
/// Does not log output; safe to call during cleanup.
pub fn uninstall_hooks_silent() {
    let Ok(hooks_dir) = get_hooks_dir() else { return };
    if !hooks_dir.exists() {
        return;
    }

    for hook_name in &["pre-commit", "pre-push"] {
        let hook_path = hooks_dir.join(hook_name);
        if hook_path.exists() && matches!(file_contains_marker(&hook_path, HOOK_MARKER), Ok(true)) {
            let hook_path_abs = fs::canonicalize(&hook_path).unwrap_or_else(|_| hook_path.clone());
            let orig_path = PathBuf::from(format!("{}.ralph.orig", hook_path_abs.display()));

            if orig_path.exists() {
                let _ = fs::rename(&orig_path, &hook_path);
            } else {
                let _ = fs::remove_file(&hook_path);
            }
        }
    }
}
