#!/usr/bin/env zsh
# lib/git_helpers.zsh - Git helper functions for ralph.zsh
# Provides: git hooks management, git wrapper for blocking commits during agent phase

# Source guard to prevent multiple loading
[[ -n "${_RALPH_GIT_HELPERS_LOADED:-}" ]] && return 0
typeset -g _RALPH_GIT_HELPERS_LOADED=1

# Dependencies
RALPH_SCRIPT_DIR="${RALPH_SCRIPT_DIR:-${0:A:h:h}}"
source "${RALPH_SCRIPT_DIR}/lib/utils.zsh"

############################################
# Git repository helpers
############################################

# Get the real git binary path (before any wrapper)
typeset -g REAL_GIT=""
typeset -g WRAPDIR=""
typeset -g HOOK_MARKER="RALPH_ZSH_MANAGED_HOOK"

# Initialize REAL_GIT if not already set
init_real_git() {
  [[ -z "$REAL_GIT" ]] && REAL_GIT="$(command -v git)"
}

require_git_repo() {
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || fail "Not inside a git repo."
}

git_snapshot() {
  git status --porcelain=v1
}

############################################
# Hook management
############################################

install_hook() {
  local hook_name="$1"
  local hook_path="$2"
  # Use absolute path for orig to work from subdirectories
  local orig_path="${hook_path:A}.ralph.orig"

  mkdir -p "${hook_path:h}"

  if [[ -f "$hook_path" ]] && ! file_contains_marker "$hook_path" "$HOOK_MARKER"; then
    cp -f "$hook_path" "$orig_path"
    chmod +x "$orig_path" || true
  fi

  cat > "$hook_path" <<EOF
#!/usr/bin/env bash
set -euo pipefail
# ${HOOK_MARKER} - generated by ralph.zsh

repo_root="\$(command git rev-parse --show-toplevel 2>/dev/null || pwd)"
if [[ -f "\$repo_root/.no_agent_commit" ]]; then
  echo "✋ ${hook_name} blocked (agent phase): .no_agent_commit exists."
  exit 1
fi

orig="${orig_path}"
if [[ -f "\$orig" ]]; then
  exec "\$orig" "\$@"
fi

exit 0
EOF
  chmod +x "$hook_path"
}

install_hooks() {
  local hooks_dir
  hooks_dir="$(git rev-parse --git-path hooks)"
  [[ -n "$hooks_dir" ]] || fail "Unable to resolve git hooks directory."
  mkdir -p "$hooks_dir"
  install_hook "Commit" "$hooks_dir/pre-commit"
  install_hook "Push" "$hooks_dir/pre-push"
}

############################################
# Git wrapper (blocks commit/push during agent phase)
############################################

enable_git_wrapper() {
  init_real_git
  WRAPDIR="$(mktemp -d)"
  cat > "$WRAPDIR/git" <<EOF
#!/usr/bin/env bash
set -euo pipefail
repo_root="\$("$REAL_GIT" rev-parse --show-toplevel 2>/dev/null || pwd)"
if [[ -f "\$repo_root/.no_agent_commit" ]]; then
  subcmd="\${1:-}"
  case "\$subcmd" in
    commit|push|tag)
      echo "✋ Blocked: git \$subcmd disabled during agent phase (.no_agent_commit present)."
      exit 1
      ;;
  esac
fi
exec "$REAL_GIT" "\$@"
EOF
  chmod +x "$WRAPDIR/git"
  export PATH="$WRAPDIR:$PATH"
}

disable_git_wrapper() {
  [[ -n "${WRAPDIR:-}" && -d "$WRAPDIR" ]] && rm -rf "$WRAPDIR" || true
}

############################################
# Agent phase management
############################################

start_agent_phase() {
  touch .no_agent_commit
  install_hooks
  enable_git_wrapper
}

end_agent_phase() {
  rm -f .no_agent_commit
}

############################################
# Reviewer commit support
############################################
# When RALPH_REVIEWER_COMMITS=1, the reviewer (Codex) is allowed
# to run git commit at the end of its phase

# Allow reviewer to commit by temporarily lifting the block
# This removes .no_agent_commit and disables the wrapper
allow_reviewer_commit() {
  rm -f .no_agent_commit
  disable_git_wrapper
}

# Re-enable commit block after reviewer phase (if needed)
block_commits_again() {
  touch .no_agent_commit
  enable_git_wrapper
}

############################################
# Hook uninstall / restore
############################################

# Uninstall a single hook by restoring original or removing
# Args: $1 = hook path (e.g., .git/hooks/pre-commit)
uninstall_hook() {
  local hook_path="$1"
  local orig_path="${hook_path:A}.ralph.orig"

  # Check if this is a Ralph-managed hook
  if [[ -f "$hook_path" ]] && file_contains_marker "$hook_path" "$HOOK_MARKER"; then
    if [[ -f "$orig_path" ]]; then
      # Restore original hook
      mv -f "$orig_path" "$hook_path"
      log_info "Restored original hook: ${hook_path:t}"
    else
      # No original to restore, just remove
      rm -f "$hook_path"
      log_info "Removed hook: ${hook_path:t}"
    fi
    return 0
  else
    log_warn "Hook not managed by Ralph: ${hook_path:t}"
    return 1
  fi
}

# Uninstall all Ralph-managed hooks
uninstall_hooks() {
  local hooks_dir
  hooks_dir="$(git rev-parse --git-path hooks 2>/dev/null)" || return 1
  [[ -d "$hooks_dir" ]] || return 0

  local restored=0
  for hook_name in pre-commit pre-push; do
    if [[ -f "$hooks_dir/$hook_name" ]]; then
      if uninstall_hook "$hooks_dir/$hook_name"; then
        ((restored++))
      fi
    fi
  done

  if [[ $restored -gt 0 ]]; then
    log_success "Uninstalled $restored Ralph hook(s)"
  else
    log_info "No Ralph hooks to uninstall"
  fi
}

# Clean up orphaned .no_agent_commit marker
# Use this if Ralph was killed and left the marker behind
cleanup_orphaned_marker() {
  local repo_root
  repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
    log_error "Not in a git repository"
    return 1
  }

  if [[ -f "$repo_root/.no_agent_commit" ]]; then
    rm -f "$repo_root/.no_agent_commit"
    log_success "Removed orphaned .no_agent_commit marker"
    return 0
  else
    log_info "No orphaned marker found"
    return 0
  fi
}
