//! Advanced help handler.
//!
//! Provides comprehensive help information including all options,
//! environment variables, templates, and examples.

use crate::colors::Colors;

/// Displays comprehensive advanced help information.
pub fn handle_help_advanced(colors: &Colors) {
    let dim = colors.dim();
    let reset = colors.reset();
    let cyan = colors.cyan();
    let yellow = colors.yellow();
    let green = colors.green();
    let bold = colors.bold();

    println!("{}", dim);
    println!("╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    println!();
    println!("{}QUICK START:{}", reset, yellow);
    println!("    1. Create PROMPT.md: ralph --init-prompt feature-spec");
    println!("    2. Run: ralph \"feat: implement my feature\"");
    println!("    3. Ralph runs developer agent → reviewer agent → auto-commits result");
    println!();
    println!("    Get started: ralph --init-global    (create config)");
    println!("                  ralph --list-templates");
    println!();
    println!("╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    println!();
    println!("{}BY TASK TYPE:{}", reset, yellow);
    println!();
    println!("    Quick Fixes (typos, small tweaks):");
    println!("        ralph -Q \"fix: typo in header\"     # Quick: 1 dev + 1 review");
    println!("        ralph -U \"fix: minor bug\"           # Rapid: 2 dev + 1 review");
    println!();
    println!("    New Features (typical development):");
    println!("        ralph -S \"feat: add login\"          # Standard: 5 dev + 2 reviews");
    println!("        ralph -T \"feat: complex feature\"    # Thorough: 10 dev + 5 reviews");
    println!();
    println!("    Major Refactoring (thorough review needed):");
    println!("        ralph -L \"refactor: core system\"    # Long: 15 dev + 10 reviews");
    println!();
    println!("    Bug Fixing with Regression Testing:");
    println!("        ralph --init-prompt bug-fix");
    println!("        # Edit PROMPT.md with bug details, then:");
    println!("        ralph -S \"fix: [issue title]\"");
    println!();
    println!("╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    println!();
    println!("{}PRESET MODES:{}", reset, yellow);
    println!("    -Q, --quick      1 dev + 1 review      (rapid prototyping)");
    println!("    -U, --rapid      2 dev + 1 review      (fast iteration)");
    println!("    -S, --standard   5 dev + 2 reviews     (default workflow)");
    println!("    -T, --thorough  10 dev + 5 reviews     (balanced but thorough)");
    println!("    -L, --long      15 dev + 10 reviews    (most thorough)");
    println!();
    println!("    Note: -D N and -R N flags always override preset values.");
    println!();
    println!("╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    println!();
    println!("{}ALL FLAGS:{}", reset, yellow);
    println!();
    println!("{}Agent Configuration:{}", reset, bold);
    println!("    -a AGENT            Developer agent (claude, codex, opencode, etc.)");
    println!("    -r AGENT            Reviewer agent (for code quality checks)");
    println!("    --preset NAME       Use preset agent combo (default, opencode)");
    println!("    --review-depth LVL  Review depth: standard, comprehensive, security, incremental");
    println!();
    println!("{}Iteration Control:{}", reset, bold);
    println!("    -D N                Developer iterations (how many times the AI tries to build)");
    println!("    -R N                Review cycles (0=skip, 1=one cycle, default: 2)");
    println!("    -Q, -U, -S, -T, -L  Preset modes (see above)");
    println!();
    println!("{}Output Control:{}", reset, bold);
    println!("    -v N / -q / -f     Verbosity: 0=quiet, 1=normal, 2=verbose, 3=full, 4=debug");
    println!("    --full             Full output mode (no truncation, same as -v3)");
    println!("    --quiet            Quiet mode (minimal output, same as -v0)");
    println!("    --debug            Debug mode (max verbosity with raw JSON, same as -v4)");
    println!();
    println!("{}Configuration:{}", reset, bold);
    println!("    -c, --config PATH   Path to config file (default: ~/.config/ralph-workflow.toml)");
    println!("    -d, --diagnose     Show system info, agent status, and config for troubleshooting");
    println!();
    println!("{}Workflow Control:{}", reset, bold);
    println!("    -i, --interactive      Prompt to create PROMPT.md from template when missing");
    println!("    --no-isolation        Keep NOTES.md and ISSUES.md between runs");
    println!("    --resume              Resume from last checkpoint (if interrupted)");
    println!("    --dry-run             Validate configuration and PROMPT.md without running agents");
    println!();
    println!("{}Initialization:{}", reset, bold);
    println!("    --init-global         Create ~/.config/ralph-workflow.toml with default settings");
    println!("    --init-prompt TPL     Create PROMPT.md from template");
    println!("    --list-templates      Show all available PROMPT.md templates");
    println!();
    println!("{}Info Commands:{}", reset, bold);
    println!("    --list-agents         Show all agents from registry and config file");
    println!("    --list-available-agents  Show only agents that are installed and available");
    println!("    --list-providers      Show OpenCode provider types and their configuration");
    println!();
    println!("{}Plumbing (for scripting):{}", reset, bold);
    println!("    --generate-commit-msg Generate message only (writes to .agent/commit-message.txt)");
    println!("    --show-commit-msg     Display generated message from .agent/commit-message.txt");
    println!("    --apply-commit        Stage all changes and commit using generated message");
    println!("    --reset-start-commit  Reset .agent/start_commit to current HEAD");
    println!();
    println!("╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    println!();
    println!("{}VERBOSITY LEVELS:{}", reset, yellow);
    println!("    0 = quiet    Minimal output, hide tool inputs (--quiet or -q)");
    println!("    1 = normal   Balanced output, show tool inputs");
    println!("    2 = verbose  Default - generous limits for full context");
    println!("    3 = full     No truncation (--full or -f)");
    println!("    4 = debug    Max verbosity with raw JSON (--debug)");
    println!();
    println!("{}ENVIRONMENT VARIABLES:{}", reset, yellow);
    println!("    RALPH_DEVELOPER_AGENT         Developer agent (from agent_chain)");
    println!("    RALPH_REVIEWER_AGENT          Reviewer agent (from agent_chain)");
    println!("    RALPH_DEVELOPER_ITERS         Developer iterations (default: 5)");
    println!("    RALPH_REVIEWER_REVIEWS        Re-review passes (default: 2)");
    println!("    RALPH_REVIEWER_JSON_PARSER    JSON parser for reviewer agent");
    println!("    RALPH_VERBOSITY               Verbosity level 0-4 (default: 2)");
    println!("    RALPH_ISOLATION_MODE          Isolation mode on/off (default: 1=on)");
    println!();
    println!("{}AVAILABLE TEMPLATES:{}", reset, yellow);
    println!("    feature-spec    For implementing new features");
    println!("    bug-fix         For fixing bugs with regression testing");
    println!("    refactor        For code refactoring and optimization");
    println!("    test            For adding or improving tests");
    println!("    docs            For documentation updates");
    println!("    quick           For small, straightforward changes");
    println!();
    println!("{}For full documentation, see:{} https://codeberg.org/mistlight/RalphWithReviewer", reset, cyan);
    println!("{}Quick reference guide:{} docs/quick-reference.md", reset, green);
    println!("╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
}
