//! Git Helper Functions
//!
//! Provides git hooks management, git wrapper for blocking commits during agent phase.

use crate::utils::{file_contains_marker, Logger};
use std::env;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::Command;

/// Marker string for Ralph-managed hooks
pub const HOOK_MARKER: &str = "RALPH_RUST_MANAGED_HOOK";

/// Git helper state
pub struct GitHelpers {
    real_git: Option<PathBuf>,
    wrapper_dir: Option<PathBuf>,
}

impl GitHelpers {
    pub fn new() -> Self {
        Self {
            real_git: None,
            wrapper_dir: None,
        }
    }

    /// Find the real git binary path
    fn init_real_git(&mut self) {
        if self.real_git.is_none() {
            if let Ok(output) = Command::new("which").arg("git").output() {
                if output.status.success() {
                    let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
                    self.real_git = Some(PathBuf::from(path));
                }
            }
        }
    }
}

impl Default for GitHelpers {
    fn default() -> Self {
        Self::new()
    }
}

/// Check if we're in a git repository
pub fn require_git_repo() -> io::Result<()> {
    let output = Command::new("git")
        .args(["rev-parse", "--is-inside-work-tree"])
        .output()?;

    if output.status.success() {
        Ok(())
    } else {
        Err(io::Error::new(
            io::ErrorKind::NotFound,
            "Not inside a git repo",
        ))
    }
}

/// Get the git repository root
pub fn get_repo_root() -> io::Result<PathBuf> {
    let output = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()?;

    if output.status.success() {
        let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
        Ok(PathBuf::from(path))
    } else {
        Err(io::Error::new(
            io::ErrorKind::NotFound,
            "Not in a git repository",
        ))
    }
}

/// Get a snapshot of the current git status
pub fn git_snapshot() -> io::Result<String> {
    let output = Command::new("git")
        .args(["status", "--porcelain=v1"])
        .output()?;

    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}

/// Get the git hooks directory path
pub fn get_hooks_dir() -> io::Result<PathBuf> {
    let output = Command::new("git")
        .args(["rev-parse", "--git-path", "hooks"])
        .output()?;

    if output.status.success() {
        let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
        Ok(PathBuf::from(path))
    } else {
        Err(io::Error::new(
            io::ErrorKind::NotFound,
            "Unable to resolve git hooks directory",
        ))
    }
}

/// Install a git hook
pub fn install_hook(hook_name: &str, hook_path: &Path) -> io::Result<()> {
    // Use absolute path for orig backup
    let hook_path_abs = fs::canonicalize(hook_path.parent().unwrap_or(Path::new(".")))?
        .join(hook_path.file_name().unwrap_or_default());
    let orig_path = format!("{}.ralph.orig", hook_path_abs.display());

    // Create hooks directory if needed
    if let Some(parent) = hook_path.parent() {
        fs::create_dir_all(parent)?;
    }

    // Backup existing hook if not already managed by Ralph
    if hook_path.exists() && !file_contains_marker(hook_path, HOOK_MARKER)? {
        fs::copy(hook_path, &orig_path)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&orig_path)?.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&orig_path, perms)?;
        }
    }

    // Write new hook
    let hook_content = format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
# {} - generated by ralph

repo_root="$(command git rev-parse --show-toplevel 2>/dev/null || pwd)"
if [[ -f "$repo_root/.no_agent_commit" ]]; then
  echo "✋ {} blocked (agent phase): .no_agent_commit exists."
  exit 1
fi

orig="{}"
if [[ -f "$orig" ]]; then
  exec "$orig" "$@"
fi

exit 0
"#,
        HOOK_MARKER, hook_name, orig_path
    );

    let mut file = File::create(hook_path)?;
    file.write_all(hook_content.as_bytes())?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(hook_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(hook_path, perms)?;
    }

    Ok(())
}

/// Install pre-commit and pre-push hooks
pub fn install_hooks() -> io::Result<()> {
    let hooks_dir = get_hooks_dir()?;
    fs::create_dir_all(&hooks_dir)?;

    install_hook("Commit", &hooks_dir.join("pre-commit"))?;
    install_hook("Push", &hooks_dir.join("pre-push"))?;

    Ok(())
}

/// Uninstall a single hook by restoring original or removing
pub fn uninstall_hook(hook_path: &Path, logger: &Logger) -> io::Result<bool> {
    let hook_path_abs = if hook_path.is_absolute() {
        hook_path.to_path_buf()
    } else {
        fs::canonicalize(hook_path.parent().unwrap_or(Path::new(".")))?
            .join(hook_path.file_name().unwrap_or_default())
    };
    let orig_path = PathBuf::from(format!("{}.ralph.orig", hook_path_abs.display()));

    // Check if this is a Ralph-managed hook
    if hook_path.exists() && file_contains_marker(hook_path, HOOK_MARKER)? {
        if orig_path.exists() {
            // Restore original hook
            fs::rename(&orig_path, hook_path)?;
            let name = hook_path.file_name().unwrap_or_default().to_string_lossy();
            logger.info(&format!("Restored original hook: {}", name));
        } else {
            // No original to restore, just remove
            fs::remove_file(hook_path)?;
            let name = hook_path.file_name().unwrap_or_default().to_string_lossy();
            logger.info(&format!("Removed hook: {}", name));
        }
        Ok(true)
    } else {
        let name = hook_path.file_name().unwrap_or_default().to_string_lossy();
        logger.warn(&format!("Hook not managed by Ralph: {}", name));
        Ok(false)
    }
}

/// Uninstall all Ralph-managed hooks
pub fn uninstall_hooks(logger: &Logger) -> io::Result<()> {
    let hooks_dir = get_hooks_dir()?;
    if !hooks_dir.exists() {
        return Ok(());
    }

    let mut restored = 0;
    for hook_name in &["pre-commit", "pre-push"] {
        let hook_path = hooks_dir.join(hook_name);
        if hook_path.exists() && uninstall_hook(&hook_path, logger)? {
            restored += 1;
        }
    }

    if restored > 0 {
        logger.success(&format!("Uninstalled {} Ralph hook(s)", restored));
    } else {
        logger.info("No Ralph hooks to uninstall");
    }

    Ok(())
}

/// Enable git wrapper that blocks commits during agent phase
pub fn enable_git_wrapper(helpers: &mut GitHelpers) -> io::Result<PathBuf> {
    helpers.init_real_git();
    let real_git = helpers
        .real_git
        .as_ref()
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "git not found"))?;

    #[allow(deprecated)]
    let wrapper_dir = tempfile::tempdir()?.into_path();
    let wrapper_path = wrapper_dir.join("git");

    let wrapper_content = format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
repo_root="$("{}" rev-parse --show-toplevel 2>/dev/null || pwd)"
if [[ -f "$repo_root/.no_agent_commit" ]]; then
  subcmd="${{1:-}}"
  case "$subcmd" in
    commit|push|tag)
      echo "✋ Blocked: git $subcmd disabled during agent phase (.no_agent_commit present)."
      exit 1
      ;;
  esac
fi
exec "{}" "$@"
"#,
        real_git.display(),
        real_git.display()
    );

    let mut file = File::create(&wrapper_path)?;
    file.write_all(wrapper_content.as_bytes())?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&wrapper_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&wrapper_path, perms)?;
    }

    // Prepend wrapper dir to PATH
    let current_path = env::var("PATH").unwrap_or_default();
    env::set_var(
        "PATH",
        format!("{}:{}", wrapper_dir.display(), current_path),
    );

    helpers.wrapper_dir = Some(wrapper_dir.clone());
    Ok(wrapper_dir)
}

/// Disable git wrapper
pub fn disable_git_wrapper(helpers: &mut GitHelpers) {
    if let Some(wrapper_dir) = helpers.wrapper_dir.take() {
        let _ = fs::remove_dir_all(&wrapper_dir);
        // Remove from PATH
        if let Ok(path) = env::var("PATH") {
            let wrapper_str = wrapper_dir.to_string_lossy();
            let new_path: String = path
                .split(':')
                .filter(|p| !p.contains(wrapper_str.as_ref()))
                .collect::<Vec<_>>()
                .join(":");
            env::set_var("PATH", new_path);
        }
    }
}

/// Start agent phase (creates marker file, installs hooks, enables wrapper)
pub fn start_agent_phase(helpers: &mut GitHelpers) -> io::Result<()> {
    File::create(".no_agent_commit")?;
    install_hooks()?;
    enable_git_wrapper(helpers)?;
    Ok(())
}

/// End agent phase (removes marker file)
pub fn end_agent_phase() -> io::Result<()> {
    let _ = fs::remove_file(".no_agent_commit");
    Ok(())
}

/// Allow reviewer to commit by temporarily lifting the block
pub fn allow_reviewer_commit(helpers: &mut GitHelpers) {
    let _ = fs::remove_file(".no_agent_commit");
    disable_git_wrapper(helpers);
}

/// Re-enable commit block after reviewer phase
pub fn block_commits_again(helpers: &mut GitHelpers) -> io::Result<()> {
    File::create(".no_agent_commit")?;
    enable_git_wrapper(helpers)?;
    Ok(())
}

/// Clean up orphaned .no_agent_commit marker
pub fn cleanup_orphaned_marker(logger: &Logger) -> io::Result<()> {
    let repo_root = get_repo_root()?;
    let marker_path = repo_root.join(".no_agent_commit");

    if marker_path.exists() {
        fs::remove_file(&marker_path)?;
        logger.success("Removed orphaned .no_agent_commit marker");
    } else {
        logger.info("No orphaned marker found");
    }

    Ok(())
}

/// Get current HEAD commit hash
pub fn get_head_commit() -> io::Result<String> {
    let output = Command::new("git").args(["rev-parse", "HEAD"]).output()?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        Ok(String::new())
    }
}

/// Get last commit message
pub fn get_last_commit_message() -> io::Result<String> {
    let output = Command::new("git")
        .args(["log", "-1", "--pretty=%s"])
        .output()?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        Ok(String::new())
    }
}

/// Stage all changes
pub fn git_add_all() -> io::Result<()> {
    let status = Command::new("git").args(["add", "-A"]).status()?;

    if status.success() {
        Ok(())
    } else {
        Err(io::Error::other("git add failed"))
    }
}

/// Create a commit
pub fn git_commit(message: &str) -> io::Result<bool> {
    let status = Command::new("git")
        .args(["commit", "-m", message])
        .status()?;

    Ok(status.success())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    // Note: Tests that change working directory need to run serially
    // Run with: cargo test -- --test-threads=1

    #[test]
    fn test_git_snapshot() {
        // Create a temp git repo
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();

        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Create an untracked file
        fs::write(dir_path.join("testfile.txt"), "test").unwrap();

        let output = Command::new("git")
            .args(["status", "--porcelain=v1"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        let snapshot = String::from_utf8_lossy(&output.stdout).to_string();
        assert!(snapshot.contains("??"));
    }

    #[test]
    fn test_install_hook() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();

        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        let hooks_dir = dir_path.join(".git/hooks");
        fs::create_dir_all(&hooks_dir).unwrap();

        let hook_path = hooks_dir.join("pre-commit");
        install_hook("Commit", &hook_path).unwrap();

        assert!(hook_path.exists());
        let content = fs::read_to_string(&hook_path).unwrap();
        assert!(content.contains(HOOK_MARKER));
    }

    #[test]
    fn test_marker_file_operations() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();
        let marker_path = dir_path.join(".no_agent_commit");

        // Create marker
        File::create(&marker_path).unwrap();
        assert!(marker_path.exists());

        // Remove marker
        fs::remove_file(&marker_path).unwrap();
        assert!(!marker_path.exists());
    }

    #[test]
    fn test_git_helpers_new() {
        let helpers = GitHelpers::new();
        assert!(helpers.real_git.is_none());
        assert!(helpers.wrapper_dir.is_none());
    }

    #[test]
    fn test_uninstall_hook_restores_original() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();
        let logger = Logger::new(crate::colors::Colors { enabled: false });

        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        let hooks_dir = dir_path.join(".git/hooks");
        fs::create_dir_all(&hooks_dir).unwrap();

        // Create an original hook
        let hook_path = hooks_dir.join("pre-commit");
        fs::write(&hook_path, "#!/bin/bash\necho 'Original hook'").unwrap();

        // Install Ralph hook (backs up original)
        install_hook("Commit", &hook_path).unwrap();

        // Verify Ralph hook is installed
        let content = fs::read_to_string(&hook_path).unwrap();
        assert!(content.contains(HOOK_MARKER));

        // Uninstall hook
        let restored = uninstall_hook(&hook_path, &logger).unwrap();
        assert!(restored);

        // Verify original is restored
        let content = fs::read_to_string(&hook_path).unwrap();
        assert!(content.contains("Original hook"));
        assert!(!content.contains(HOOK_MARKER));
    }

    #[test]
    fn test_uninstall_hook_removes_when_no_original() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();
        let logger = Logger::new(crate::colors::Colors { enabled: false });

        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        let hooks_dir = dir_path.join(".git/hooks");
        fs::create_dir_all(&hooks_dir).unwrap();

        // Install Ralph hook (no original)
        let hook_path = hooks_dir.join("pre-commit");
        install_hook("Commit", &hook_path).unwrap();

        // Uninstall hook
        let removed = uninstall_hook(&hook_path, &logger).unwrap();
        assert!(removed);

        // Verify hook is removed
        assert!(!hook_path.exists());
    }

    #[test]
    fn test_install_hook_uses_absolute_path() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();

        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        let hooks_dir = dir_path.join(".git/hooks");
        fs::create_dir_all(&hooks_dir).unwrap();

        // Create an existing hook
        let hook_path = hooks_dir.join("pre-commit");
        fs::write(&hook_path, "#!/bin/bash\nexit 0").unwrap();

        // Install Ralph hook
        install_hook("TestHook", &hook_path).unwrap();

        // Read the installed hook content
        let content = fs::read_to_string(&hook_path).unwrap();

        // The orig= line should contain an absolute path (starts with /)
        assert!(content.contains("orig=\"/"));
    }

    // NOTE: Tests that change working directory need to run serially
    // because set_current_dir affects the entire process.
    // For now, we test these functions more directly without changing directories.

    #[test]
    fn test_start_end_agent_phase_marker() {
        // Test the marker file operations without changing directory
        let dir = TempDir::new().unwrap();
        let marker_path = dir.path().join(".no_agent_commit");

        // Simulate start_agent_phase marker creation
        File::create(&marker_path).unwrap();
        assert!(marker_path.exists());

        // Simulate end_agent_phase marker removal
        fs::remove_file(&marker_path).unwrap();
        assert!(!marker_path.exists());
    }

    #[test]
    fn test_allow_reviewer_commit_removes_marker() {
        // Test that the marker removal logic works
        let dir = TempDir::new().unwrap();
        let marker_path = dir.path().join(".no_agent_commit");

        // Create marker
        File::create(&marker_path).unwrap();
        assert!(marker_path.exists());

        // Remove marker (simulating allow_reviewer_commit)
        fs::remove_file(&marker_path).unwrap();
        assert!(!marker_path.exists());
    }

    #[test]
    fn test_block_commits_creates_marker() {
        // Test that marker creation works
        let dir = TempDir::new().unwrap();
        let marker_path = dir.path().join(".no_agent_commit");

        // Create marker (simulating block_commits_again)
        File::create(&marker_path).unwrap();
        assert!(marker_path.exists());

        // Clean up
        fs::remove_file(&marker_path).unwrap();
    }

    #[test]
    fn test_cleanup_orphaned_marker() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();
        let _logger = Logger::new(crate::colors::Colors { enabled: false });

        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Create marker
        let marker_path = dir_path.join(".no_agent_commit");
        File::create(&marker_path).unwrap();
        assert!(marker_path.exists());

        // Test cleanup by simulating the operation
        fs::remove_file(&marker_path).unwrap();
        assert!(!marker_path.exists());

        // Test when marker doesn't exist (should not fail)
        let result = std::panic::catch_unwind(|| {
            let _ = fs::remove_file(Path::new("/nonexistent/.no_agent_commit"));
        });
        assert!(result.is_ok()); // should not panic
    }

    #[test]
    fn test_commit_verification_detects_new_commit() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();

        // Init git repo
        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Configure git user
        Command::new("git")
            .args(["config", "user.email", "test@test.com"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.name", "Test"])
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Create initial commit
        fs::write(dir_path.join("file.txt"), "initial").unwrap();
        Command::new("git")
            .args(["add", "file.txt"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["commit", "-m", "initial"])
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Capture HEAD before
        let head_before = Command::new("git")
            .args(["rev-parse", "HEAD"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        let head_before = String::from_utf8_lossy(&head_before.stdout)
            .trim()
            .to_string();

        // Make a new commit
        fs::write(dir_path.join("file.txt"), "changed").unwrap();
        Command::new("git")
            .args(["add", "file.txt"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["commit", "-m", "second commit"])
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Capture HEAD after
        let head_after = Command::new("git")
            .args(["rev-parse", "HEAD"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        let head_after = String::from_utf8_lossy(&head_after.stdout)
            .trim()
            .to_string();

        // Verify detection
        assert_ne!(head_before, head_after);
    }

    #[test]
    fn test_commit_verification_detects_no_commit() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();

        // Init git repo
        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Configure git user
        Command::new("git")
            .args(["config", "user.email", "test@test.com"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.name", "Test"])
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Create initial commit
        fs::write(dir_path.join("file.txt"), "initial").unwrap();
        Command::new("git")
            .args(["add", "file.txt"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["commit", "-m", "initial"])
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Capture HEAD (no new commit made)
        let head_before = Command::new("git")
            .args(["rev-parse", "HEAD"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        let head_before = String::from_utf8_lossy(&head_before.stdout)
            .trim()
            .to_string();

        let head_after = Command::new("git")
            .args(["rev-parse", "HEAD"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        let head_after = String::from_utf8_lossy(&head_after.stdout)
            .trim()
            .to_string();

        // Verify no change detected
        assert_eq!(head_before, head_after);
    }

    #[test]
    fn test_get_head_commit_function() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();

        // Init git repo
        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Configure git user
        Command::new("git")
            .args(["config", "user.email", "test@test.com"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.name", "Test"])
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Create initial commit
        fs::write(dir_path.join("file.txt"), "test").unwrap();
        Command::new("git")
            .args(["add", "file.txt"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["commit", "-m", "test commit"])
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Get HEAD using git directly
        let head = Command::new("git")
            .args(["rev-parse", "HEAD"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        let head_str = String::from_utf8_lossy(&head.stdout).trim().to_string();

        // Should be a valid commit hash (40 characters)
        assert_eq!(head_str.len(), 40);
    }

    #[test]
    fn test_get_last_commit_message_function() {
        let dir = TempDir::new().unwrap();
        let dir_path = dir.path();

        // Init git repo
        Command::new("git")
            .arg("init")
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Configure git user
        Command::new("git")
            .args(["config", "user.email", "test@test.com"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["config", "user.name", "Test"])
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Create commit with specific message
        fs::write(dir_path.join("file.txt"), "test").unwrap();
        Command::new("git")
            .args(["add", "file.txt"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        Command::new("git")
            .args(["commit", "-m", "feat: test commit message"])
            .current_dir(dir_path)
            .output()
            .unwrap();

        // Get last commit message using git directly
        let msg = Command::new("git")
            .args(["log", "-1", "--pretty=%s"])
            .current_dir(dir_path)
            .output()
            .unwrap();
        let msg_str = String::from_utf8_lossy(&msg.stdout).trim().to_string();

        assert_eq!(msg_str, "feat: test commit message");
    }
}
